prepare:
  data: "../data/Ethos_Dataset_Binary.csv"
  target_col: "isHate"
  text_col: "comment"
  max_features: 2000
train:
  logs_path: "logs/"
  train_data_path: "train_data.pkl"
  val_data_path: "val_data.pkl"
  model_name: "model"
  hyperparams: 
      iterations: trial.suggest_int("iterations", 1000, 3000)
      learning_rate: trial.suggest_float("learning_rate", 0.01, 0.5, log=True)
      colsample_bylevel: trial.suggest_float("colsample_bylevel", 0.01, 0.1, log=True)
      l2_leaf_reg: trial.suggest_float("l2_leaf_reg", 1e-8, 100.0, log=True)
      depth: trial.suggest_int("depth", 1, 12)
  n_trials: 100
  timeout: 600
evaluate:
  model_path: "model.pkl"
  model_tuned_path: "model_tuned.pkl"
  test_data_path: "test_data.pkl"